language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Ie0dW1TQcNE6s8Kq7MLdpsPLi1s245rXIpn65PRT2ODdaIlrc9lJetAq8eKapfntwhBPRjGPb7Mg1r8inIjzYK0NGJNCmqlk/6Opyx5tgFoVXV6FnDCiou757c0gDMF6pOYhpYhfPGiD32DIUk7pxV7iVE6da/ruWU4dZ9ITFIGtcq//9pUo8q5zFGOyXmC07CffHyb5DOcyvc3sYSD5FCTmdZEYR4om6Nwq9VMinhuZLHjl0zaC2/N65HR1+zT7ysEp6JQWsDBMdIrB7LuUYRBqjij73MbRrOkGD3u8bnFcYxZMxdJS8UpnXZRPzi+NB+4MnI+VlMq9If8TiaPyuIqbkO3qefScsPG19t3sXMSpueL4e+tuDrfRaAb96X/R+EF/lNdcHt3keYRu8zJ6SO5WZvwf1f2x3ZOcCwySTjliXEBVogThycyxCpaGdzzsRvJpOOQnQSBrQQdkuFDVH5vgtJsa24IuD737qPQXZ9Ix7jwXx4JmMfChfeOEtQVgMYb4hTcyFJPoGhjx+W+kmuTfSpKxDUEdDdZAzwvGAi888glkjs7QH08gm1/1spuZ0kw5QfWvGMwDFJe2reXsDKuO+y1kyF/yxhvCAtCzqcxvBxhs3TtzNk8C2QCbcixoo4uEc8byEDqhJpqUX+E4ps8Vi3LidkKC97foqGdnUz0=
  app: pure-meadow-90794
  on:
    repo: NickFoden/blog-app-mongoose-challenge-solution
